import uuid
from django.db import models
from django.conf import settings
from accounts.models import Workspace

class BrandKit(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); workspace=models.OneToOneField(Workspace,on_delete=models.CASCADE,related_name='brand_kit'); brand_name=models.CharField(max_length=200,blank=True); brand_description=models.TextField(blank=True); primary_color=models.CharField(max_length=20,blank=True); secondary_color=models.CharField(max_length=20,blank=True); accent_color=models.CharField(max_length=20,blank=True); font_primary=models.CharField(max_length=150,blank=True); tone_of_voice=models.TextField(blank=True); default_call_to_action=models.CharField(max_length=255,blank=True); logo_url=models.URLField(blank=True); updated_at=models.DateTimeField(auto_now=True)
class BrandAsset(models.Model):
 CATEGORIES=[(x,x) for x in ['product','packaging','lifestyle','logo','persona','reference_ad','template','background','icon','other']]
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); workspace=models.ForeignKey(Workspace,on_delete=models.CASCADE,related_name='assets'); category=models.CharField(max_length=30,choices=CATEGORIES); name=models.CharField(max_length=255); file=models.FileField(upload_to='brand-assets/'); is_favorite=models.BooleanField(default=False); metadata=models.JSONField(default=dict,blank=True); uploaded_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True); created_at=models.DateTimeField(auto_now_add=True)
class Product(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); workspace=models.ForeignKey(Workspace,on_delete=models.CASCADE,related_name='products'); name=models.CharField(max_length=255); short_description=models.CharField(max_length=500,blank=True); original_price=models.DecimalField(max_digits=12,decimal_places=2,null=True,blank=True); sale_price=models.DecimalField(max_digits=12,decimal_places=2,null=True,blank=True); currency_code=models.CharField(max_length=3,default='PEN'); primary_benefit=models.TextField(blank=True); target_customer=models.TextField(blank=True); product_url=models.URLField(blank=True); image=models.ImageField(upload_to='products/',blank=True); benefits=models.JSONField(default=list,blank=True); features=models.JSONField(default=list,blank=True); is_active=models.BooleanField(default=True); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
class CreativeRecipe(models.Model):
 CONTENT_TYPES=[(x,x) for x in ['flyer','social_post','story','banner','carousel','short_video','product_video']]
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); workspace=models.ForeignKey(Workspace,on_delete=models.CASCADE,null=True,blank=True,related_name='recipes'); name=models.CharField(max_length=255); description=models.TextField(blank=True); content_type=models.CharField(max_length=30,choices=CONTENT_TYPES); creative_angle=models.CharField(max_length=50,default='offer'); prompt_template=models.TextField(); layout_rules=models.JSONField(default=dict,blank=True); is_system_recipe=models.BooleanField(default=False); is_active=models.BooleanField(default=True)
class AdProject(models.Model):
 CONTENT_TYPES=CreativeRecipe.CONTENT_TYPES; STATUSES=[(x,x) for x in ['draft','ready','generating','completed','archived','cancelled']]
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); workspace=models.ForeignKey(Workspace,on_delete=models.CASCADE,related_name='projects'); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT); product=models.ForeignKey(Product,on_delete=models.SET_NULL,null=True,blank=True); recipe=models.ForeignKey(CreativeRecipe,on_delete=models.SET_NULL,null=True,blank=True); name=models.CharField(max_length=255); content_type=models.CharField(max_length=30,choices=CONTENT_TYPES); headline=models.TextField(blank=True); offer_text=models.TextField(blank=True); call_to_action=models.CharField(max_length=255,blank=True); target_audience=models.TextField(blank=True); aspect_ratio=models.CharField(max_length=20,default='4:5'); quality_mode=models.CharField(max_length=30,default='standard'); requested_variations=models.PositiveIntegerField(default=1); status=models.CharField(max_length=20,choices=STATUSES,default='draft'); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
class GenerationJob(models.Model):
 STATUSES=[(x,x) for x in ['queued','processing','completed','failed','cancelled']]
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); project=models.ForeignKey(AdProject,on_delete=models.CASCADE,related_name='jobs'); requested_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT); provider_connection=models.ForeignKey('integrations.AIProviderConnection',on_delete=models.PROTECT,null=True,blank=True,related_name='generation_jobs'); provider=models.CharField(max_length=100,default='mock'); model_name=models.CharField(max_length=200,default='mock-ad-generator'); provider_request_id=models.CharField(max_length=255,blank=True); estimated_cost_usd=models.DecimalField(max_digits=12,decimal_places=6,null=True,blank=True); actual_cost_usd=models.DecimalField(max_digits=12,decimal_places=6,null=True,blank=True); prompt=models.TextField(); parameters=models.JSONField(default=dict,blank=True); number_of_outputs=models.PositiveIntegerField(default=1); status=models.CharField(max_length=20,choices=STATUSES,default='queued'); error_message=models.TextField(blank=True); created_at=models.DateTimeField(auto_now_add=True); completed_at=models.DateTimeField(null=True,blank=True)
class GeneratedAsset(models.Model):
 TYPES=[(x,x) for x in ['image','video','audio','thumbnail','subtitle','background','composition']]
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); job=models.ForeignKey(GenerationJob,on_delete=models.CASCADE,related_name='assets'); project=models.ForeignKey(AdProject,on_delete=models.CASCADE,related_name='generated_assets'); asset_type=models.CharField(max_length=30,choices=TYPES); file=models.FileField(upload_to='generated/'); thumbnail_url=models.URLField(blank=True); prompt_used=models.TextField(blank=True); metadata=models.JSONField(default=dict,blank=True); is_favorite=models.BooleanField(default=False); created_at=models.DateTimeField(auto_now_add=True)
class AssetFeedback(models.Model):
 id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False); asset=models.ForeignKey(GeneratedAsset,on_delete=models.CASCADE,related_name='feedback'); user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE); feedback_type=models.CharField(max_length=20,choices=[('like','Like'),('dislike','Dislike'),('favorite','Favorite')]); feedback_reason=models.CharField(max_length=100,blank=True); comment=models.TextField(blank=True); created_at=models.DateTimeField(auto_now_add=True)
 class Meta: constraints=[models.UniqueConstraint(fields=['asset','user','feedback_type'],name='unique_asset_feedback')]
