# Generated by Django 5.2.16 on 2026-07-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_creditmovement_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditmovement',
            name='generation_job',
        ),
        migrations.RemoveField(
            model_name='creditmovement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creditmovement',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_credits',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='credit_limit_override',
        ),
        migrations.DeleteModel(
            name='CreditBalance',
        ),
        migrations.DeleteModel(
            name='CreditMovement',
        ),
    ]
