# Generated by Django 5.2.16 on 2026-07-24 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_companyprofile_created_at_companyprofile_logo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('inherit', 'Heredar'), ('free', 'Gratuito'), ('blocked', 'Bloqueado')], default='inherit', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_user_access_policies', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('inherit', 'Heredar'), ('free', 'Gratuito'), ('blocked', 'Bloqueado')], default='inherit', max_length=12)),
                ('seat_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workspace_access_policies', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_policy_updated', 'Política de usuario actualizada'), ('workspace_policy_updated', 'Política de workspace actualizada'), ('member_updated', 'Miembro actualizado')], db_index=True, max_length=40)),
                ('target_type', models.CharField(db_index=True, max_length=40)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='access_cont_target__db4f0f_idx')],
            },
        ),
    ]
