# Generated by Django 5.2.16 on 2026-07-12 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('product', 'product'), ('packaging', 'packaging'), ('lifestyle', 'lifestyle'), ('logo', 'logo'), ('persona', 'persona'), ('reference_ad', 'reference_ad'), ('template', 'template'), ('background', 'background'), ('icon', 'icon'), ('other', 'other')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='brand-assets/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('brand_description', models.TextField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('font_primary', models.CharField(blank=True, max_length=150)),
                ('tone_of_voice', models.TextField(blank=True)),
                ('default_call_to_action', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('flyer', 'flyer'), ('social_post', 'social_post'), ('story', 'story'), ('banner', 'banner'), ('carousel', 'carousel'), ('short_video', 'short_video'), ('product_video', 'product_video')], max_length=30)),
                ('creative_angle', models.CharField(default='offer', max_length=50)),
                ('prompt_template', models.TextField()),
                ('layout_rules', models.JSONField(blank=True, default=dict)),
                ('is_system_recipe', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AdProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('flyer', 'flyer'), ('social_post', 'social_post'), ('story', 'story'), ('banner', 'banner'), ('carousel', 'carousel'), ('short_video', 'short_video'), ('product_video', 'product_video')], max_length=30)),
                ('headline', models.TextField(blank=True)),
                ('offer_text', models.TextField(blank=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('target_audience', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(default='4:5', max_length=20)),
                ('quality_mode', models.CharField(default='standard', max_length=30)),
                ('requested_variations', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('generating', 'generating'), ('completed', 'completed'), ('archived', 'archived'), ('cancelled', 'cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.workspace')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.creativerecipe')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mock', max_length=100)),
                ('model_name', models.CharField(default='mock-ad-generator', max_length=150)),
                ('prompt', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('number_of_outputs', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='studio.adproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('thumbnail', 'thumbnail'), ('subtitle', 'subtitle'), ('background', 'background'), ('composition', 'composition')], max_length=30)),
                ('file', models.FileField(upload_to='generated/')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('prompt_used', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assets', to='studio.adproject')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.generationjob')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(default='PEN', max_length=3)),
                ('primary_benefit', models.TextField(blank=True)),
                ('target_customer', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='adproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.product'),
        ),
        migrations.CreateModel(
            name='AssetFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('favorite', 'Favorite')], max_length=20)),
                ('feedback_reason', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='studio.generatedasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'user', 'feedback_type'), name='unique_asset_feedback')],
            },
        ),
    ]
