# Generated by Django 5.2.16 on 2026-07-16 21:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


ANGLE_NAMES = {
    'problem_solution': 'Problema y solución', 'benefit': 'Beneficio',
    'offer': 'Oferta', 'urgency': 'Urgencia', 'scarcity': 'Escasez',
    'comparison': 'Comparación', 'testimonial': 'Testimonio',
    'features': 'Características', 'lifestyle': 'Estilo de vida',
    'premium': 'Premium', 'minimalist': 'Minimalista',
    'educational': 'Educativo', 'emotional': 'Emocional',
}


def seed_and_link_creative_angles(apps, schema_editor):
    CreativeAngle = apps.get_model('studio', 'CreativeAngle')
    CreativeRecipe = apps.get_model('studio', 'CreativeRecipe')
    angles = {}
    for code, name in ANGLE_NAMES.items():
        angle, _ = CreativeAngle.objects.get_or_create(code=code, defaults={'name': name})
        angles[code] = angle
    for recipe in CreativeRecipe.objects.all():
        code = recipe.creative_angle_legacy or 'offer'
        recipe.creative_angle = angles.get(code, angles['offer'])
        recipe.save(update_fields=['creative_angle'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_created_at_companyprofile_logo_url_and_more'),
        ('studio', '0002_generationjob_byok_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeAngle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('problem_solution', 'problem_solution'), ('benefit', 'benefit'), ('offer', 'offer'), ('urgency', 'urgency'), ('scarcity', 'scarcity'), ('comparison', 'comparison'), ('testimonial', 'testimonial'), ('features', 'features'), ('lifestyle', 'lifestyle'), ('premium', 'premium'), ('minimalist', 'minimalist'), ('educational', 'educational'), ('emotional', 'emotional')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('example_headline', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='creativerecipe',
            old_name='creative_angle',
            new_name='creative_angle_legacy',
        ),
        migrations.AddField(
            model_name='adproject',
            name='campaign_theme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adproject',
            name='focus_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adproject',
            name='message_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adproject',
            name='resolution',
            field=models.CharField(default='1K', max_length=20),
        ),
        migrations.AddField(
            model_name='adproject',
            name='use_brand_kit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='font_secondary',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='logo_dark_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='logo_light_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creativerecipe',
            name='copy_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='creativerecipe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='creativerecipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativerecipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creativerecipe',
            name='visual_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='generation_purpose',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='negative_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_products', to='studio.brandasset'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.CreateModel(
            name='AdTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout_schema', models.JSONField(blank=True, default=dict)),
                ('editable_elements', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='studio.brandasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_templates', to='accounts.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='adproject',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studio.adtemplate'),
        ),
        migrations.CreateModel(
            name='BrandRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_colors', models.JSONField(blank=True, default=list)),
                ('forbidden_colors', models.JSONField(blank=True, default=list)),
                ('allowed_fonts', models.JSONField(blank=True, default=list)),
                ('required_elements', models.JSONField(blank=True, default=list)),
                ('forbidden_elements', models.JSONField(blank=True, default=list)),
                ('preferred_terms', models.JSONField(blank=True, default=list)),
                ('forbidden_terms', models.JSONField(blank=True, default=list)),
                ('logo_position_preferences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_kit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='studio.brandkit')),
            ],
        ),
        migrations.AddField(
            model_name='adproject',
            name='creative_angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studio.creativeangle'),
        ),
        migrations.AddField(
            model_name='creativerecipe',
            name='creative_angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='studio.creativeangle'),
        ),
        migrations.RunPython(seed_and_link_creative_angles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='creativerecipe',
            name='creative_angle_legacy',
        ),
        migrations.CreateModel(
            name='DesignComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_width', models.IntegerField()),
                ('canvas_height', models.IntegerField()),
                ('background_type', models.CharField(blank=True, max_length=50)),
                ('background_value', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='studio.adproject')),
                ('base_generated_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.generatedasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=50)),
                ('text_content', models.TextField(blank=True)),
                ('x_position', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('y_position', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rotation', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('z_index', models.IntegerField(db_index=True, default=0)),
                ('font_family', models.CharField(blank=True, max_length=150)),
                ('font_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('font_weight', models.CharField(blank=True, max_length=30)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('alignment', models.CharField(blank=True, max_length=30)),
                ('opacity', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.brandasset')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='studio.designcomposition')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('webp', 'webp'), ('mp4', 'mp4'), ('mov', 'mov'), ('pdf', 'pdf')], max_length=10)),
                ('export_resolution', models.CharField(blank=True, max_length=50)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.designcomposition')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('generated_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.generatedasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInputAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_role', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_assets', to='studio.adproject')),
                ('brand_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_inputs', to='studio.brandasset')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aspect_ratio', models.CharField(default='9:16', max_length=20)),
                ('fps', models.IntegerField(default=30)),
                ('voiceover_enabled', models.BooleanField(default=False)),
                ('music_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_project', to='studio.adproject')),
            ],
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_order', models.IntegerField()),
                ('scene_type', models.CharField(blank=True, max_length=50)),
                ('duration_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visual_prompt', models.TextField(blank=True)),
                ('text_overlay', models.TextField(blank=True)),
                ('voiceover_text', models.TextField(blank=True)),
                ('transition_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.generatedasset')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.brandasset')),
                ('video_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='studio.videoproject')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_styles', models.JSONField(blank=True, default=list)),
                ('preferred_backgrounds', models.JSONField(blank=True, default=list)),
                ('preferred_compositions', models.JSONField(blank=True, default=list)),
                ('preferred_text_density', models.CharField(blank=True, max_length=50)),
                ('preferred_product_scale', models.CharField(blank=True, max_length=50)),
                ('learned_preferences', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AssetVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation_instruction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_generated_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_variations', to='studio.generatedasset')),
                ('variation_generated_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_variations', to='studio.generatedasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_generated_asset', 'variation_generated_asset'), name='unique_asset_variation')],
            },
        ),
        migrations.AddConstraint(
            model_name='designcomposition',
            constraint=models.UniqueConstraint(fields=('ad_project', 'version'), name='unique_project_composition_version'),
        ),
        migrations.AddConstraint(
            model_name='projectinputasset',
            constraint=models.UniqueConstraint(fields=('ad_project', 'brand_asset', 'input_role'), name='unique_project_input_asset_role'),
        ),
        migrations.AddConstraint(
            model_name='videoscene',
            constraint=models.UniqueConstraint(fields=('video_project', 'scene_order'), name='unique_video_scene_order'),
        ),
    ]
