# Generated by Django 5.2.16 on 2026-07-19 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_created_at_companyprofile_logo_url_and_more'),
        ('studio', '0005_recipe_template_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='creative-references/')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_references', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('purpose', models.CharField(choices=[('style', 'Style'), ('composition', 'Composition'), ('lighting', 'Lighting'), ('color', 'Color'), ('typography', 'Typography'), ('pose', 'Pose'), ('mood', 'Mood')], max_length=50)),
                ('ad_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='studio.adproject')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.creativereference')),
            ],
        ),
    ]
