# Generated by Django 5.2.16 on 2026-07-24 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_product_image_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='prompt_modifier',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GenerationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('queued', 'queued'), ('processing', 'processing'), ('completed', 'completed'), ('partial', 'partial'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='queued', max_length=20)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('failed_jobs', models.PositiveIntegerField(default=0)),
                ('estimated_credits', models.PositiveIntegerField(default=0)),
                ('consumed_credits', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_batches', to='studio.adproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='studio.generationbatch'),
        ),
        migrations.AddIndex(
            model_name='generationbatch',
            index=models.Index(fields=['project', 'status'], name='studio_gene_project_f09a08_idx'),
        ),
        migrations.AddIndex(
            model_name='generationbatch',
            index=models.Index(fields=['status', '-created_at'], name='studio_gene_status_5f4850_idx'),
        ),
    ]
