# Generated by Django 5.2.16 on 2026-07-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_generationjob_cancel_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationbatch',
            name='consumed_credits',
        ),
        migrations.RemoveField(
            model_name='generationbatch',
            name='estimated_credits',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='credits_consumed',
        ),
    ]
