# Generated by Django 5.2.16 on 2026-07-31 04:24

import django.db.models.deletion
from django.db import migrations, models


PURPOSES = [
    ("background", "Background"),
    ("logo", "Logo"),
    ("icon", "Icon"),
    ("lifestyle", "Lifestyle"),
    ("persona", "Persona"),
    ("pose", "Pose"),
    ("mood", "Mood"),
    ("packaging", "Packaging"),
    ("template", "Template"),
    ("style", "Style"),
    ("composition", "Composition"),
    ("lighting", "Lighting"),
    ("color", "Color"),
    ("typography", "Typography"),
]


def seed_purposes(apps, schema_editor):
    Purpose = apps.get_model("studio", "Purpose")
    for code, label in PURPOSES:
        Purpose.objects.update_or_create(code=code, defaults={"label": label})


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_remove_generationbatch_consumed_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('background', 'Background'), ('logo', 'Logo'), ('icon', 'Icon'), ('lifestyle', 'Lifestyle'), ('persona', 'Persona'), ('pose', 'Pose'), ('mood', 'Mood'), ('packaging', 'Packaging'), ('template', 'Template'), ('style', 'Style'), ('composition', 'Composition'), ('lighting', 'Lighting'), ('color', 'Color'), ('typography', 'Typography')], max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
            ],
        ),
        migrations.RunPython(seed_purposes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='adproject',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='adproject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='adproject',
            name='quality_mode',
        ),
        migrations.RemoveField(
            model_name='adproject',
            name='requested_variations',
        ),
        migrations.RemoveField(
            model_name='adproject',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='brandasset',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='brandrule',
            name='logo_position_preferences',
        ),
        migrations.RemoveField(
            model_name='creativerecipe',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='actual_cost_usd',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='estimated_cost_usd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='creative_reference',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'template'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='studio.creativereference'),
        ),
        migrations.AddField(
            model_name='creativereference',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'lifestyle'), ('persona', 'persona'), ('reference_ad', 'reference_ad'), ('template', 'template'), ('background', 'background')], default='reference_ad', max_length=30),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='campaign_theme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='creative_angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.creativeangle'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='focus_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='message_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='offer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.product'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.creativerecipe'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.adtemplate'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='use_brand_kit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='input_role',
            field=models.CharField(choices=[('background', 'Fondo'), ('lifestyle_reference', 'Referencia de estilo de vida'), ('character_reference', 'Referencia de personaje'), ('template', 'Plantilla'), ('packaging', 'Empaque'), ('reference_ad', 'Referencia publicitaria')], default='reference_ad', max_length=50),
        ),
        migrations.AlterField(
            model_name='adtemplate',
            name='format',
            field=models.CharField(choices=[('square', 'Cuadrado'), ('portrait', 'Vertical'), ('landscape', 'Horizontal'), ('widescreen', 'Panorámico'), ('vertical_fullscreen', 'Vertical pantalla completa'), ('instagram_post_square', 'Instagram · Post cuadrado'), ('instagram_post_portrait', 'Instagram · Post vertical'), ('instagram_post_landscape', 'Instagram · Post horizontal'), ('instagram_story', 'Instagram · Story'), ('instagram_reel', 'Instagram · Reel'), ('instagram_carousel_square', 'Instagram · Carrusel cuadrado'), ('instagram_carousel_portrait', 'Instagram · Carrusel vertical'), ('facebook_post_square', 'Facebook · Post cuadrado'), ('facebook_post_landscape', 'Facebook · Post horizontal'), ('facebook_story', 'Facebook · Story'), ('facebook_cover', 'Facebook · Portada'), ('facebook_event_cover', 'Facebook · Portada de evento'), ('facebook_ad_square', 'Facebook Ads · Cuadrado'), ('facebook_ad_portrait', 'Facebook Ads · Vertical'), ('facebook_ad_landscape', 'Facebook Ads · Horizontal'), ('linkedin_post_square', 'LinkedIn · Post cuadrado'), ('linkedin_post_portrait', 'LinkedIn · Post vertical'), ('linkedin_post_landscape', 'LinkedIn · Post horizontal'), ('linkedin_link_preview', 'LinkedIn · Vista previa de enlace'), ('linkedin_profile_cover', 'LinkedIn · Portada de perfil'), ('linkedin_company_cover', 'LinkedIn · Portada de empresa'), ('linkedin_article_cover', 'LinkedIn · Portada de artículo'), ('tiktok_video', 'TikTok · Video vertical'), ('tiktok_image_post', 'TikTok · Publicación de imagen'), ('tiktok_ad_vertical', 'TikTok Ads · Vertical'), ('tiktok_ad_square', 'TikTok Ads · Cuadrado'), ('tiktok_ad_landscape', 'TikTok Ads · Horizontal'), ('youtube_thumbnail', 'YouTube · Miniatura'), ('youtube_video', 'YouTube · Video horizontal'), ('youtube_short', 'YouTube · Short'), ('youtube_channel_banner', 'YouTube · Banner de canal'), ('youtube_podcast_cover', 'YouTube · Portada de pódcast'), ('x_post_square', 'X · Post cuadrado'), ('x_post_landscape', 'X · Post horizontal'), ('x_header', 'X · Portada de perfil'), ('pinterest_pin', 'Pinterest · Pin estándar'), ('pinterest_square', 'Pinterest · Pin cuadrado'), ('pinterest_long_pin', 'Pinterest · Pin largo'), ('display_banner_300x250', 'Display · Rectángulo mediano'), ('display_banner_336x280', 'Display · Rectángulo grande'), ('display_banner_728x90', 'Display · Leaderboard'), ('display_banner_970x250', 'Display · Billboard'), ('display_banner_160x600', 'Display · Skyscraper'), ('display_banner_300x600', 'Display · Media página'), ('display_banner_320x50', 'Display · Banner móvil'), ('display_banner_320x100', 'Display · Banner móvil grande'), ('flyer_a4_portrait', 'Flyer A4 · Vertical'), ('flyer_a4_landscape', 'Flyer A4 · Horizontal'), ('presentation_16_9', 'Presentación · 16:9'), ('presentation_4_3', 'Presentación · 4:3'), ('email_header', 'Email · Cabecera'), ('website_hero', 'Sitio web · Hero')], default='portrait', max_length=60),
        ),
        migrations.AlterField(
            model_name='adtemplate',
            name='source_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'template'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='studio.brandasset'),
        ),
        migrations.AlterField(
            model_name='brandasset',
            name='category',
            field=models.CharField(choices=[('product', 'product'), ('packaging', 'packaging'), ('lifestyle', 'lifestyle'), ('logo', 'logo'), ('persona', 'persona'), ('reference_ad', 'reference_ad'), ('template', 'template'), ('background', 'background'), ('icon', 'icon')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='brandkit',
            name='logo_dark_url',
        ),
        migrations.RemoveField(
            model_name='brandkit',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='brandkit',
            name='logo_light_url',
        ),
        migrations.AddField(
            model_name='brandkit',
            name='logo_dark_url',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'logo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_kits_dark_logo', to='studio.brandasset'),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='logo_light_url',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'logo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_kits_light_logo', to='studio.brandasset'),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='logo_url',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'logo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_kits_logo', to='studio.brandasset'),
        ),
        migrations.AlterField(
            model_name='projectinputasset',
            name='input_role',
            field=models.CharField(choices=[('product_image', 'Imagen del producto'), ('logo', 'Logo'), ('background', 'Fondo'), ('lifestyle_reference', 'Referencia de estilo de vida'), ('character_reference', 'Referencia de personaje'), ('template', 'Plantilla'), ('packaging', 'Empaque'), ('reference_ad', 'Referencia publicitaria'), ('icon', 'Icono')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='projectreference',
            name='purpose',
        ),
        migrations.AddField(
            model_name='projectinputasset',
            name='purpose',
            field=models.ManyToManyField(blank=True, related_name='input_assets', to='studio.purpose'),
        ),
        migrations.AddField(
            model_name='projectreference',
            name='purpose',
            field=models.ManyToManyField(blank=True, related_name='project_references', to='studio.purpose'),
        ),
    ]
