# Generated by Django 5.2.16 on 2026-07-31 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_purpose_remove_adproject_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designcomposition',
            name='unique_project_composition_version',
        ),
        migrations.RemoveConstraint(
            model_name='videoscene',
            name='unique_video_scene_order',
        ),
        migrations.RemoveField(
            model_name='designcomposition',
            name='ad_project',
        ),
        migrations.RemoveField(
            model_name='designcomposition',
            name='base_generated_asset',
        ),
        migrations.RemoveField(
            model_name='designcomposition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='export',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='ad_project',
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='video_project',
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='generated_asset',
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='source_asset',
        ),
        migrations.RemoveField(
            model_name='generatedasset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='generatedasset',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='workspacepreference',
            name='preferred_backgrounds',
        ),
        migrations.RemoveField(
            model_name='workspacepreference',
            name='preferred_compositions',
        ),
        migrations.RemoveField(
            model_name='workspacepreference',
            name='preferred_product_scale',
        ),
        migrations.RemoveField(
            model_name='workspacepreference',
            name='preferred_styles',
        ),
        migrations.RemoveField(
            model_name='workspacepreference',
            name='preferred_text_density',
        ),
        migrations.CreateModel(
            name='GenerationJobInputAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_role', models.CharField(choices=[('product_image', 'Imagen del producto'), ('logo', 'Logo'), ('background', 'Fondo'), ('lifestyle_reference', 'Referencia de estilo de vida'), ('character_reference', 'Referencia de personaje'), ('template', 'Plantilla'), ('packaging', 'Empaque'), ('reference_ad', 'Referencia publicitaria'), ('icon', 'Icono')], max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_job_inputs', to='studio.brandasset')),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_assets', to='studio.generationjob')),
                ('purpose', models.ManyToManyField(blank=True, related_name='generation_job_input_assets', to='studio.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJobReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('input_role', models.CharField(choices=[('background', 'Fondo'), ('lifestyle_reference', 'Referencia de estilo de vida'), ('character_reference', 'Referencia de personaje'), ('template', 'Plantilla'), ('packaging', 'Empaque'), ('reference_ad', 'Referencia publicitaria')], default='reference_ad', max_length=50)),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='studio.generationjob')),
                ('purpose', models.ManyToManyField(blank=True, related_name='generation_job_references', to='studio.purpose')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_job_references', to='studio.creativereference')),
            ],
        ),
        migrations.DeleteModel(
            name='CompositionElement',
        ),
        migrations.DeleteModel(
            name='DesignComposition',
        ),
        migrations.DeleteModel(
            name='VideoProject',
        ),
        migrations.DeleteModel(
            name='VideoScene',
        ),
        migrations.AddConstraint(
            model_name='generationjobinputasset',
            constraint=models.UniqueConstraint(fields=('generation_job', 'brand_asset', 'input_role'), name='unique_generation_job_input_asset_role'),
        ),
    ]
