# Generated by Django 5.2.16 on 2026-07-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_remove_designcomposition_ad_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativereference',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'lifestyle'), ('persona', 'persona'), ('reference_ad', 'reference_ad'), ('template', 'template'), ('background', 'background'), ('packaging', 'packaging'), ('icon', 'icon')], default='reference_ad', max_length=30),
        ),
        migrations.AlterField(
            model_name='generationjobreference',
            name='input_role',
            field=models.CharField(choices=[('background', 'Fondo'), ('lifestyle_reference', 'Referencia de estilo de vida'), ('character_reference', 'Referencia de personaje'), ('template', 'Plantilla'), ('packaging', 'Empaque'), ('icon', 'Icono'), ('reference_ad', 'Referencia publicitaria')], default='reference_ad', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectreference',
            name='input_role',
            field=models.CharField(choices=[('background', 'Fondo'), ('lifestyle_reference', 'Referencia de estilo de vida'), ('character_reference', 'Referencia de personaje'), ('template', 'Plantilla'), ('packaging', 'Empaque'), ('icon', 'Icono'), ('reference_ad', 'Referencia publicitaria')], default='reference_ad', max_length=50),
        ),
    ]
