# Generated by Codex on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0012_alter_creativereference_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationbatch",
            name="session_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="generationbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                    ("partial", "partial"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="enqueued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="session_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="generationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
