# Generated by Django 5.2.16 on 2026-08-06 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_created_at_companyprofile_logo_url_and_more'),
        ('studio', '0013_generation_draft_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='composed_prompt',
            field=models.TextField(blank=True, help_text='Prompt final producido por Gemini en la Etapa 2.', null=True),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='prompt',
            field=models.TextField(help_text='Brief determinístico producido por la Etapa 1.'),
        ),
        migrations.CreateModel(
            name='BrandIntelligenceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona', models.TextField()),
                ('pain_point', models.TextField()),
                ('angle', models.TextField()),
                ('visual_direction', models.TextField(blank=True)),
                ('emotion', models.CharField(blank=True, max_length=150)),
                ('copy_hook', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_intelligence_profiles', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='bip_ws_active_idx')],
            },
        ),
    ]
