# Generated by Django 5.2.16 on 2026-08-07 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_generationjob_composed_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtemplate',
            name='copy_structure',
            field=models.TextField(blank=True, help_text='Jerarquía y distribución recomendada del copy.'),
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='do_rules',
            field=models.JSONField(blank=True, default=list, help_text='Reglas visuales o compositivas que deben respetarse.'),
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='dont_rules',
            field=models.JSONField(blank=True, default=list, help_text='Reglas visuales o compositivas que deben evitarse.'),
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='prompt_guidance',
            field=models.TextField(blank=True, help_text='Guía reutilizable para convertir esta plantilla en instrucciones de generación.'),
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='visual_structure',
            field=models.TextField(blank=True, help_text='Descripción estructurada de la composición visual de la plantilla.'),
        ),
        migrations.CreateModel(
            name='AdTemplateExampleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gemini_vision_notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_images', to='studio.adtemplate')),
                ('image', models.ForeignKey(limit_choices_to={'category': 'template'}, on_delete=django.db.models.deletion.PROTECT, related_name='template_example_usages', to='studio.creativereference')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['ad_template', 'sort_order'], name='tpl_example_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('ad_template', 'image'), name='uniq_template_example')],
            },
        ),
    ]
