# Generated by Django 5.2.16 on 2026-08-07 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_created_at_companyprofile_logo_url_and_more'),
        ('studio', '0015_adtemplate_copy_structure_adtemplate_do_rules_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_ads_requested', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ready', 'Listo'), ('generated', 'Generado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='ready', max_length=20)),
                ('plan_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_concept_plans', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_plans', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='concept_ws_status_idx'), models.Index(fields=['workspace', '-created_at'], name='concept_ws_created_idx')],
            },
        ),
    ]
