# Generated by Django 5.2.16 on 2026-08-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_conceptplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptplan',
            name='project',
            field=models.ForeignKey(blank=True, help_text='AdProject que proporciona producto, recursos, referencias y contexto de producción al plan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concept_plans', to='studio.adproject'),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='concept_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_batch', to='studio.conceptplan'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='body_copy_primary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='body_copy_variant_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='concept_index',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Índice 1-based del concepto dentro del ConceptPlan que originó el job.', null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='format_used',
            field=models.ForeignKey(blank=True, help_text='Plantilla seleccionada por el Concept Planner para este concepto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_generation_jobs', to='studio.adtemplate'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='hook_variant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='profile_used',
            field=models.ForeignKey(blank=True, help_text='Perfil de Brand Intelligence utilizado para producir este anuncio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='studio.brandintelligenceprofile'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='rationale',
            field=models.TextField(blank=True),
        ),
    ]
