# Generated by Django 5.2.16 on 2026-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_conceptplan_project_generationbatch_concept_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtemplate',
            name='layout_constraints',
            field=models.JSONField(blank=True, default=dict, help_text='Restricciones estructurales duras y verificables de la plantilla. Deben limitarse a reglas de layout que no deban ser reinterpretadas creativamente.'),
        ),
        migrations.AlterField(
            model_name='adtemplate',
            name='layout_schema',
            field=models.JSONField(blank=True, default=dict, help_text='LEGACY: esquema estructural anterior. Se conserva temporalmente durante la migración hacia layout_constraints.'),
        ),
    ]
