# Generated by Django 5.2.16 on 2026-08-08 19:44

from django.db import migrations


def migrate_legacy_data(
    apps,
    schema_editor,
):
    AdProject = apps.get_model(
        "studio",
        "AdProject",
    )

    GenerationJob = apps.get_model(
        "studio",
        "GenerationJob",
    )

    AdTemplate = apps.get_model(
        "studio",
        "AdTemplate",
    )

    AdTemplateExampleImage = apps.get_model(
        "studio",
        "AdTemplateExampleImage",
    )

    # -------------------------------------------------
    # 1. Preservar target_audience de proyectos antiguos
    # -------------------------------------------------

    for project in AdProject.objects.all().iterator():
        audience = (project.target_audience or "").strip()

        if not audience:
            continue

        GenerationJob.objects.filter(
            project_id=project.id,
            profile_used__isnull=True,
            target_audience="",
        ).update(
            target_audience=audience,
        )

    # -------------------------------------------------
    # 2. layout_schema -> layout_constraints
    # -------------------------------------------------

    for template in AdTemplate.objects.all().iterator():
        if template.layout_constraints:
            continue

        legacy = template.layout_schema or {}

        if not isinstance(
            legacy,
            dict,
        ):
            continue

        constraints = {}

        canvas_mode = legacy.get("canvas_mode")

        if canvas_mode:
            constraints["canvas_mode"] = canvas_mode

        if "allow_split_screen" in legacy:
            constraints["allow_split_screen"] = bool(legacy["allow_split_screen"])

        if "allow_collage" in legacy:
            constraints["allow_collage"] = bool(legacy["allow_collage"])

        max_products = legacy.get("max_product_instances")

        if isinstance(max_products, int) and max_products > 0:
            constraints["max_product_instances"] = max_products

        required_elements = legacy.get("required_elements")

        if isinstance(
            required_elements,
            list,
        ):
            constraints["required_elements"] = required_elements

        if constraints:
            template.layout_constraints = constraints

            template.save(
                update_fields=[
                    "layout_constraints",
                ]
            )

    # -------------------------------------------------
    # 3. creative_reference -> ExampleImage
    # -------------------------------------------------

    for template in AdTemplate.objects.exclude(creative_reference_id=None).iterator():

        reference_id = template.creative_reference_id

        already_exists = AdTemplateExampleImage.objects.filter(
            ad_template_id=template.id,
            image_id=reference_id,
        ).exists()

        if already_exists:
            continue

        max_sort_order = (
            AdTemplateExampleImage.objects.filter(
                ad_template_id=template.id,
            )
            .order_by("-sort_order")
            .values_list(
                "sort_order",
                flat=True,
            )
            .first()
        )

        next_sort_order = (max_sort_order + 1) if max_sort_order is not None else 0

        AdTemplateExampleImage.objects.create(
            ad_template_id=template.id,
            image_id=reference_id,
            sort_order=next_sort_order,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "studio",
            "0018_adtemplate_layout_constraints_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_data,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="adproject",
            name="target_audience",
        ),
    ]
