# Generated by Django 5.2.16 on 2026-08-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_migrate_template_source_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtemplate',
            name='creative_reference',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='layout_schema',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='source_asset',
        ),
    ]
