'use client';

import { useEffect, useMemo, useState } from 'react';

import Nav from '@/components/Nav';
import { api, ensureWorkspace } from '@/lib/api';

const emptyForm = { title:'', source:'', author:'', url:'', notes:'', tags:'' };

export default function ReferencesPage() {
  const [references,setReferences]=useState([]),[form,setForm]=useState(emptyForm),[image,setImage]=useState(null),[preview,setPreview]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  async function load(){await ensureWorkspace();const data=await api('/studio/creative-references/');setReferences(data.results||data)}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const tagCount=useMemo(()=>form.tags.split(',').filter(item=>item.trim()).length,[form.tags]);
  function chooseImage(file){if(preview)URL.revokeObjectURL(preview);setImage(file||null);setPreview(file?URL.createObjectURL(file):'')}
  async function submit(event){event.preventDefault();if(!image)return;setBusy(true);setError('');try{const payload=new FormData();Object.entries(form).forEach(([key,value])=>payload.append(key,key==='tags'?JSON.stringify(value.split(',').map(tag=>tag.trim()).filter(Boolean)):value));payload.append('image',image);await api('/studio/creative-references/',{method:'POST',body:payload});setForm(emptyForm);chooseImage(null);setOpen(false);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function remove(item){if(!window.confirm(`¿Eliminar “${item.title}” de la biblioteca?`))return;try{await api(`/studio/creative-references/${item.id}/`,{method:'DELETE'});await load()}catch(e){setError(e.message)}}
  return <><Nav privateNav/><main className="container references-page"><header className="references-hero"><div><span className="eyebrow">Creative intelligence</span><h1>Referencias</h1><p>Construye una memoria visual curada para orientar estilo, luz, composición y atmósfera.</p></div><button className="btn" onClick={()=>setOpen(value=>!value)}>{open?'Cerrar':'+ Nueva referencia'}</button></header>{error&&<div className="error">{error}</div>}{open&&<form className="reference-form" onSubmit={submit}><div className="reference-upload"><input type="file" accept="image/*" required onChange={event=>chooseImage(event.target.files?.[0])}/>{preview?<img src={preview} alt="Vista previa"/>:<div><strong>Selecciona una imagen</strong><span>PNG, JPG o WebP</span></div>}</div><div className="reference-fields"><label><span>Título</span><input className="input" required value={form.title} onChange={e=>update('title',e.target.value)}/></label><div><label><span>Fuente</span><input className="input" value={form.source} onChange={e=>update('source',e.target.value)} placeholder="Behance, campaña, editorial…"/></label><label><span>Autor</span><input className="input" value={form.author} onChange={e=>update('author',e.target.value)}/></label></div><label><span>URL original</span><input className="input" type="url" value={form.url} onChange={e=>update('url',e.target.value)}/></label><label><span>Notas curatoriales</span><textarea className="input" value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Qué debe aprender el modelo de esta referencia."/></label><label><span>Etiquetas <small>{tagCount}</small></span><input className="input" value={form.tags} onChange={e=>update('tags',e.target.value)} placeholder="editorial, luz suave, composición…"/></label><button className="btn" disabled={busy||!image}>{busy?'Guardando…':'Guardar referencia'}</button></div></form>}<section className="reference-library"><header><span>{references.length} referencias</span><p>Seleccionables desde cualquier proyecto del workspace.</p></header><div className="reference-grid">{references.map(item=><article key={item.id}><div><img src={item.image_url} alt={item.title}/><button onClick={()=>remove(item)} aria-label={`Eliminar ${item.title}`}>×</button></div><section><span>{item.source||'Referencia visual'}</span><h2>{item.title}</h2><p>{item.notes||item.author||'Sin notas curatoriales.'}</p><div>{(item.tags||[]).map(tag=><small key={tag}>{tag}</small>)}</div></section></article>)}{!references.length&&!open&&<div className="references-empty"><h2>Tu tablero está listo</h2><p>Agrega la primera imagen que defina una dirección visual valiosa.</p><button className="btn" onClick={()=>setOpen(true)}>Crear referencia</button></div>}</div></section></main></>;
}
